name: Deploy app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          VITE_JITSI_PUBLIC_URL: ${{ vars.VITE_JITSI_PUBLIC_URL }}
          VITE_XMPP_DOMAIN: ${{ vars.VITE_XMPP_DOMAIN }}
          VITE_XMPP_MUC_DOMAIN: ${{ vars.VITE_XMPP_MUC_DOMAIN }}
          VITE_SESSION_PREFIX: ${{ vars.VITE_SESSION_PREFIX }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
